services:
  mysql_db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'e-commerce'
      MYSQL_USER: 'vato'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: